name: Publish Package

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false 
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install

      - run: yarn run types

      - name: Get Version
        run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - run: yarn publish --new-version "$VERSION" --access public --no-git-tag-version
