name: Publish Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          always-auth: true
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install

      - run: yarn run types

      - name: Get Version
        run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - run: yarn publish --new-version "$VERSION" --access public --no-git-tag-version
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN }}
